apiVersion: batch/v1
kind: Job
metadata:
  name: "puksta1"
  namespace: default
spec:
  backoffLimit: 4
  template:
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: mlflow-worker-key
      containers:
        - name: dreamer
          image: eu.gcr.io/human-ui/dreamer:puksta1
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow.threethirds.ai
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          command: ["python"]
          args:
            [
              "dreamer.py",
              "--task",
              "atari_breakout",
              "--dataset_balance",
              "True",
              "--train_steps",
              "100",
              "--time_limit",
              "2e3",
              "--deter_size",
              "200",
              "--stoch_size",
              "30",
              "--pcont",
              "True",
              "--kl_scale",
              "0.1",
              "--horizon",
              "10",
              "--action_dist",
              "onehot",
              "--expl",
              "epsilon_greedy",
              "--expl_amount",
              "0.4",
              "--expl_decay",
              "100000.0",
              "--expl_min",
              "0.1",
              "--num_units",
              "300",
              "--steps",
              "1e6",
              "--action_repeat",
              "2",
            ]
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              memory: 16000Mi
              cpu: 3000m
              nvidia.com/gpu: 1
      restartPolicy: Never